### ISSUE TITLE
Interference with markdown-it-attrs - some formulas missing

### ISSUE THREAD

**Issue by tk-100** [widcardw/markdown-it-asciimath#2]
When using your module in combination with [markdown-it-attrs](https://github.com/arve0/markdown-it-attrs), some formulas are missing. In order to reproduce the error I created the following text (three lines with line breaks):

~~~
End of line, followed by newline: ``a+b``

End of test text
~~~

In this case the formula a+b isn't visible, tested in in firefox, chrome and safari. The error seems to occur whenever the formula is at the end of a line that is followed by a blank line. 

Unfortunately I don't know if the cause is in your module or markdown-it-attrs.

Versions used:

~~~
    "markdown-it": "^13.0.1",
    "markdown-it-attrs": "^4.1.6",
    "@widcardw/markdown-it-asciimath": "^0.5.3"
~~~

**Comment by widcardw** [comment]
I don't know why this happens, but if I do not use double backtick to mark the formula, it works fine. Maybe it's because the asciimath render rule only pushes the `<math>` as a self-closing token, and then in markdown-it-attrs pipe, the self-closing will be transformed like: moving the asciimath content to tag attributes. 

However, markdown-it-katex works fine. I'll try to fix this problem!

**Comment by widcardw** [comment]
Now in my test cases, it works fine. Please try `v0.5.4` and report any problem here!

**Comment by tk-100** [comment]
Thanks a lot - everything works fine :-)

PS: Just for your information, I also successfully tested the followings modules in combination with yours:

~~~
    "markdown-it-blockquote-cite": "^0.1.3",
    "markdown-it-deflist": "^2.1.0",
    "markdown-it-footnote": "^3.0.3",
    "markdown-it-sub": "^1.0.0",
    "markdown-it-sup": "^1.0.0",
    "markdown-it-task-list": "^0.1.2",
~~~
